export const types = {
  
  OPEN_MODAL_CREATE_TASK: 'OPEN_MODAL_CREATE_TASK',
  OPEN_MODAL_EDIT_TASK:   'OPEN_MODAL_EDIT_TASK',
  OPEN_MODAL_LOGIN:       'OPEN_MODAL_LOGIN',
  
  CLOSE_MODAL_CREATE_TASK: 'CLOSE_MODAL_CREATE_TASK',
  CLOSE_MODAL_EDIT_TASK:   'CLOSE_MODAL_EDIT_TASK',
  CLOSE_MODAL_LOGIN:       'CLOSE_MODAL_LOGIN',
  
}