export const types = {
  
  OPEN_MODAL_ADD_NEW_TASK: 'OPEN_MODAL_ADD_NEW_TASK',
  OPEN_MODAL_LOGIN: 'OPEN_MODAL_LOGIN',
  
  CLOSE_MODAL_ADD_NEW_TASK: 'CLOSE_MODAL_ADD_NEW_TASK',
  CLOSE_MODAL_LOGIN: 'CLOSE_MODAL_LOGIN'
  
}