export const type = {
  // Sync
  CHANGE_PAGE:             'CHANGE_PAGE',
  CREATE_TASK:             'CREATE_TASK',
  FILL_TASKS:              'FILL_TASKS',
  HIDE_MODAL_EDIT_TASK:    'HIDE_MODAL_EDIT_TASK',
  HIDE_MODAL_NEW_TASK:     'HIDE_MODAL_NEW_TASK',
  HIDE_MODAL_PREVIEW_TASK: 'HIDE_MODAL_PREVIEW_TASK',
  LOAD_DATA_PREVIEW_TASK:  'LOAD_DATA_PREVIEW_TASK',
  LOAD_IMAGE_PREVIEW_TASK: 'LOAD_IMAGE_PREVIEW_TASK',
  SHOW_MODAL_EDIT_TASK:    'SHOW_MODAL_EDIT_TASK',
  SHOW_MODAL_NEW_TASK:     'SHOW_MODAL_NEW_TASK',
  SHOW_MODAL_PREVIEW_TASK: 'SHOW_MODAL_PREVIEW_TASK',
  SORT_ORDER_TASK:         'SORT_ORDER_TASK',
  SORT_TASK:               'SORT_TASK',
  UPDATE_TASK:             'UPDATE_TASK',
  // Asyn
  CHANGE_PAGE_ASYNC:       'CHANGE_PAGE_ASYNC',
  CREATE_TASK_ASYNC:       'CREATE_TASK_ASYNC',
  FETCH_TASKS_ASYNC:       'FETCH_TASKS_ASYNC',
  SORT_ORDER_TASK_ASYNC:   'SORT_ORDER_TASK_ASYNC',
  SORT_TASK_ASYNC:         'SORT_TASK_ASYNC',
  UPDATE_TASK_ASYNC:       'UPDATE_TASK_ASYNC',
};
