export const types = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  FAIL:    '_FAIL',
  
  FETCH_TASKS: 'FETCH_TASKS',
  CREATE_TASK: 'CREATE_TASK',
  EDIT_TASK:   'EDIT_TASK',
  
  CHANGE_PAGE:   'CHANGE_PAGE',
  CHANGE_FILTER: 'CHANGE_FILTER',
}
